// AUTO-GENERATED by tools/embed_packs_gc.py -- do not edit
#pragma once
#include "platform_types.h"

#define PACK_COUNT 1

extern const u8  atlas_png_default[];
extern const u32 atlas_png_default_size;
#define atlas_tile_size_default 16

static const char* g_pack_names[PACK_COUNT] = {
    "default",
};
static const u8* g_pack_atlases[PACK_COUNT] = {
    atlas_png_default,
};
static const u32 g_pack_sizes[PACK_COUNT] = {
    atlas_png_default_size,
};
static const int g_pack_tile_sizes[PACK_COUNT] = {
    atlas_tile_size_default,
};