// AUTO-GENERATED by tools/embed_packs_gc.py -- do not edit
#pragma once
#include "platform_types.h"

#define PACK_COUNT 3

extern const u8  atlas_png_default[];
extern const u32 atlas_png_default_size;
#define atlas_tile_size_default 16
extern const u8  atlas_png_template[];
extern const u32 atlas_png_template_size;
#define atlas_tile_size_template 16
extern const u8  atlas_png_test[];
extern const u32 atlas_png_test_size;
#define atlas_tile_size_test 64

extern const char* const g_pack_names[PACK_COUNT];
extern const u8*   const g_pack_atlases[PACK_COUNT];
extern const u32   g_pack_sizes[PACK_COUNT];
extern const int   g_pack_tile_sizes[PACK_COUNT];
