// AUTO-GENERATED by tools/gen_atlas.py -- do not edit
#ifndef ATLAS_REGIONS_H
#define ATLAS_REGIONS_H

#define TEX_GRASS_TOP 0
#define TEX_GRASS_SIDE 1
#define TEX_DIRT 2
#define TEX_STONE 3
#define TEX_WOOD 4
#define TEX_LEAVES 5
#define TEX_COUNT 6

#ifdef ATLAS_REGIONS_IMPL
static const float atlas_uvs[TEX_COUNT][4] = {
    {0.000000f, 0.000000f, 0.250000f, 0.500000f}, // TEX_GRASS_TOP
    {0.250000f, 0.000000f, 0.500000f, 0.500000f}, // TEX_GRASS_SIDE
    {0.500000f, 0.000000f, 0.750000f, 0.500000f}, // TEX_DIRT
    {0.750000f, 0.000000f, 1.000000f, 0.500000f}, // TEX_STONE
    {0.000000f, 0.500000f, 0.250000f, 1.000000f}, // TEX_WOOD
    {0.250000f, 0.500000f, 0.500000f, 1.000000f}, // TEX_LEAVES
};
#endif

#endif // ATLAS_REGIONS_H
