#pragma once
// AUTO-GENERATED by tools/embed_packs.py

#define PACK_COUNT 3

extern const unsigned char atlas_png_default[];
extern const unsigned int  atlas_png_default_size;
extern const int           atlas_tile_size_default;
extern const unsigned char atlas_png_template[];
extern const unsigned int  atlas_png_template_size;
extern const int           atlas_tile_size_template;
extern const unsigned char atlas_png_test[];
extern const unsigned int  atlas_png_test_size;
extern const int           atlas_tile_size_test;

// Pack name table
static const char* g_pack_names[PACK_COUNT] = {
    "default",
    "template",
    "test",
};
static const unsigned char* g_pack_atlases[PACK_COUNT] = {
    atlas_png_default,
    atlas_png_template,
    atlas_png_test,
};
static const unsigned int g_pack_sizes[PACK_COUNT] = {
    atlas_png_default_size,
    atlas_png_template_size,
    atlas_png_test_size,
};
static const int g_pack_tile_sizes[PACK_COUNT] = {
    atlas_tile_size_default,
    atlas_tile_size_template,
    atlas_tile_size_test,
};
