#!/usr/bin/env python3
"""
embed_packs.py - Generates a C++ file embedding all resource pack atlases.
Each pack gets a symbol: atlas_png_<packname>[] and atlas_png_<packname>_size.
Also generates atlas_png[] pointing to the active pack.
Usage: python3 tools/embed_packs.py <build_data_dir>
"""
import os, sys, json

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT       = os.path.join(SCRIPT_DIR, '..')
PACKS_DIR  = os.path.join(ROOT, 'data', 'resource_packs')
ACTIVE_F   = os.path.join(ROOT, 'data', 'active_pack.txt')
ATLAS_PATH = os.path.join(ROOT, 'data', 'textures', 'atlas.png')

def get_active():
    if os.path.exists(ACTIVE_F):
        with open(ACTIVE_F) as f:
            n = f.read().strip()
        if n: return n
    return 'default'

def safe_sym(name):
    return name.replace('-','_').replace(' ','_').replace('.','_')

def main():
    out_dir = sys.argv[1] if len(sys.argv) > 1 else 'build/pc/data'
    os.makedirs(out_dir, exist_ok=True)

    active = get_active()
    packs = []

    if os.path.isdir(PACKS_DIR):
        for d in sorted(os.listdir(PACKS_DIR)):
            pack_path = os.path.join(PACKS_DIR, d)
            if not os.path.isdir(pack_path): continue
            atlas = os.path.join(pack_path, 'atlas.png')
            meta_path = os.path.join(pack_path, 'pack.json')
            meta = {}
            if os.path.exists(meta_path):
                with open(meta_path) as f:
                    try: meta = json.load(f)
                    except: pass

            # Generate atlas for this pack if missing
            if not os.path.exists(atlas):
                print(f"  generating atlas for pack '{d}'...")
                import subprocess
                subprocess.run([sys.executable,
                    os.path.join(os.path.dirname(ATLAS_PATH), '..', '..',
                                 'tools', 'gen_atlas.py'), '--pack', d],
                    check=False)
                # gen_atlas writes to data/textures/atlas.png — copy to pack
                if os.path.exists(ATLAS_PATH):
                    import shutil
                    shutil.copy(ATLAS_PATH, atlas)
                    # Restore active pack atlas
                    if d != active:
                        subprocess.run([sys.executable,
                            os.path.join(os.path.dirname(ATLAS_PATH), '..', '..',
                                         'tools', 'gen_atlas.py')],
                            check=False)

            # For active pack, always use the freshly generated atlas
            if d == active and os.path.exists(ATLAS_PATH):
                import shutil
                shutil.copy(ATLAS_PATH, atlas)

            if os.path.exists(atlas):
                packs.append((d, atlas, meta))

    # Fallback — just embed main atlas as 'default'
    if not packs and os.path.exists(ATLAS_PATH):
        packs = [('default', ATLAS_PATH, {'tile_size': 16})]

    out_cpp = os.path.join(out_dir, 'atlas_png.cpp')
    out_h   = os.path.join(ROOT, 'include', 'atlas_packs.h')

    with open(out_cpp, 'w') as f:
        f.write('// AUTO-GENERATED by tools/embed_packs.py\n')
        f.write('#include <stddef.h>\n\n')

        for pack_name, atlas_path, meta in packs:
            sym = safe_sym(pack_name)
            tile_size = meta.get('tile_size', 16)
            data = open(atlas_path, 'rb').read()
            f.write(f'// Pack: {pack_name} (tile_size={tile_size})\n')
            f.write(f'const unsigned char atlas_png_{sym}[] = {{\n')
            for i in range(0, len(data), 16):
                chunk = data[i:i+16]
                f.write('    ' + ', '.join(f'0x{b:02x}' for b in chunk) + ',\n')
            f.write(f'}};\n')
            f.write(f'const unsigned int atlas_png_{sym}_size = {len(data)};\n')
            f.write(f'const int atlas_tile_size_{sym} = {tile_size};\n\n')

        # Active pack aliases
        active_sym = safe_sym(active) if any(p[0]==active for p in packs) else safe_sym(packs[0][0])
        f.write(f'// Active pack: {active}\n')
        f.write(f'const unsigned char* atlas_png = atlas_png_{active_sym};\n')
        f.write(f'const unsigned int atlas_png_size = atlas_png_{active_sym}_size;\n')
        f.write(f'int g_atlas_tile_size = atlas_tile_size_{active_sym};\n\n')
        # Write g_pack_* definitions directly into atlas_png.cpp
        f.write('#include "gc_compat.h"\n')
        f.write('#include "atlas_packs.h"\n\n')
        f.write(f'const char* g_pack_names[PACK_COUNT] = {{\n')
        for pack_name, _, _ in packs:
            f.write(f'    "{pack_name}",\n')
        f.write('};\n')
        f.write(f'const u8* g_pack_atlases[PACK_COUNT] = {{\n')
        for pack_name, _, _ in packs:
            sym2 = safe_sym(pack_name)
            f.write(f'    (const u8*)atlas_png_{sym2},\n')
        f.write('};\n')
        f.write(f'const u32 g_pack_sizes[PACK_COUNT] = {{\n')
        for pack_name, _, _ in packs:
            sym2 = safe_sym(pack_name)
            f.write(f'    atlas_png_{sym2}_size,\n')
        f.write('};\n')
        f.write(f'const int g_pack_tile_sizes[PACK_COUNT] = {{\n')
        for pack_name, _, _ in packs:
            sym2 = safe_sym(pack_name)
            f.write(f'    atlas_tile_size_{sym2},\n')
        f.write('};\n')

    with open(out_h, 'w') as f:
        f.write('#pragma once\n')
        f.write('// AUTO-GENERATED by tools/embed_packs.py\n\n')
        f.write('#include "platform_types.h"\n\n')
        f.write(f'#define PACK_COUNT {len(packs)}\n\n')
        for pack_name, _, meta in packs:
            sym = safe_sym(pack_name)
            tile_size = int(meta.get('tile_size', 16))
            f.write(f'extern const unsigned char atlas_png_{sym}[];\n')
            f.write(f'extern const unsigned int  atlas_png_{sym}_size;\n')
            f.write(f'#define atlas_tile_size_{sym} {tile_size}\n')
        f.write('\n')
        f.write('extern const char* g_pack_names[PACK_COUNT];\n')
        f.write('extern const u8*   g_pack_atlases[PACK_COUNT];\n')
        f.write('extern const u32   g_pack_sizes[PACK_COUNT];\n')
        f.write('extern const int   g_pack_tile_sizes[PACK_COUNT];\n')
    
    print(f"Embedded {len(packs)} pack(s): {[p[0] for p in packs]}")
    print(f"Active: {active}")

if __name__ == '__main__':
    main()