// AUTO-GENERATED by tools/embed_packs_gc.py -- do not edit
#include "platform_types.h"
#include "atlas_packs.h"

static const char s_packname_default[] = "default";
static const char s_packname_test[] = "test";
const char* const g_pack_names[PACK_COUNT] = {
    s_packname_default,
    s_packname_test,
};
const u8* const g_pack_atlases[PACK_COUNT] = {
    atlas_png_default,
    atlas_png_test,
};
const u32 g_pack_sizes[PACK_COUNT] = {
    atlas_png_default_size,
    atlas_png_test_size,
};
const int g_pack_tile_sizes[PACK_COUNT] = {
    atlas_tile_size_default,
    atlas_tile_size_test,
};
