#include "sound.h"
#include <string.h>

// ─────────────────────────────────────────────────────────────────────────────
#ifdef _PC
// ── PC: SDL_mixer ─────────────────────────────────────────────────────────────
#include <SDL2/SDL_mixer.h>
#include <stdio.h>

static Mix_Chunk* s_chunks[SFX_COUNT] = {};

void Sound_Init(void) {
    if (Mix_OpenAudio(44100, MIX_DEFAULT_FORMAT, 2, 1024) < 0) {
        fprintf(stderr, "SDL_mixer init failed: %s\n", Mix_GetError());
        return;
    }
    // Try several paths to find sound files
    const char* paths[SFX_COUNT][3] = {
        { "data/sounds/minecraft-glass-break.mp3",
          "../data/sounds/minecraft-glass-break.mp3",
          "../../data/sounds/minecraft-glass-break.mp3" },
        { "data/sounds/minecraft-hit-sfx.mp3",
          "../data/sounds/minecraft-hit-sfx.mp3",
          "../../data/sounds/minecraft-hit-sfx.mp3" },
        { "data/sounds/explode1.mp3",
          "../data/sounds/explode1.mp3",
          "../../data/sounds/explode1.mp3" },
    };
    for (int i = 0; i < SFX_COUNT; i++) {
        for (int j = 0; j < 3; j++) {
            s_chunks[i] = Mix_LoadWAV(paths[i][j]);
            if (s_chunks[i]) break;
        }
        if (!s_chunks[i])
            fprintf(stderr, "Sound %d not found\n", i);
    }
}

void Sound_Play(SoundID id) {
    if (id < SFX_COUNT && s_chunks[id])
        Mix_PlayChannel(-1, s_chunks[id], 0);
}

void Sound_Shutdown(void) {
    for (int i = 0; i < SFX_COUNT; i++)
        if (s_chunks[i]) Mix_FreeChunk(s_chunks[i]);
    Mix_CloseAudio();
}

// ─────────────────────────────────────────────────────────────────────────────
#else
// ── GC/Wii: ASND + embedded PCM ───────────────────────────────────────────────
// Audio files must be converted to raw signed 16-bit stereo PCM at 44100Hz
// and embedded via bin2s (same pipeline as the atlas).
// File naming: sounds/block_break.raw, sounds/player_hit.raw, sounds/explode.raw
// If a sound file is missing, that slot is silently skipped.

#include <asndlib.h>
#include <gccore.h>

// External PCM data (generated by bin2s from .raw files)
// These are weak-referenced so the build doesn't fail if files are missing
#ifdef __cplusplus
extern "C" {
#endif
// Block break
extern const u8  block_break_raw[]     __attribute__((weak));
extern const u32 block_break_raw_size  __attribute__((weak));
// Player hit
extern const u8  player_hit_raw[]      __attribute__((weak));
extern const u32 player_hit_raw_size   __attribute__((weak));
// Explosion
extern const u8  explode_raw[]         __attribute__((weak));
extern const u32 explode_raw_size      __attribute__((weak));
#ifdef __cplusplus
}
#endif

typedef struct {
    const u8* data;
    u32       size;
} SfxEntry;

static SfxEntry s_sfx[SFX_COUNT];

void Sound_Init(void) {
    ASND_Init();
    ASND_Pause(0);

    s_sfx[SFX_BLOCK_BREAK] = { block_break_raw,  block_break_raw  ? block_break_raw_size  : 0 };
    s_sfx[SFX_PLAYER_HIT]  = { player_hit_raw,   player_hit_raw   ? player_hit_raw_size   : 0 };
    s_sfx[SFX_EXPLODE]     = { explode_raw,       explode_raw      ? explode_raw_size      : 0 };
}

void Sound_Play(SoundID id) {
    if (id >= SFX_COUNT) return;
    const SfxEntry& e = s_sfx[id];
    if (!e.data || e.size == 0) return;
    // Find a free voice (1-7, leave 0 for music later)
    for (int v = 1; v < 8; v++) {
        if (ASND_StatusVoice(v) == SND_UNUSED) {
            ASND_SetVoice(v, VOICE_STEREO_16BIT, 44100, 0,
                          (void*)e.data, e.size,
                          200, 200, NULL);
            break;
        }
    }
}

void Sound_Shutdown(void) {
    ASND_End();
}

#endif // _PC