#define ATLAS_REGIONS_IMPL
#include "textures.h"
#include "atlas_regions.h"
#include "platform_types.h"
#ifndef _PC
#include <gccore.h>
#include <string.h>
#include <malloc.h>
#include <png.h>
#else
#include "platform/pc/gc_compat.h"
#include <string.h>
#include <stdlib.h>
#include <png.h>
#endif

// Pack atlas data — generated by embed_packs.py
#include "atlas_packs.h"

static GXTexObj s_atlasObjs[PACK_COUNT];
static int      s_atlasW[PACK_COUNT];
static int      s_atlasH[PACK_COUNT];
static int      s_currentPack = 0;
static int      s_inited[PACK_COUNT] = {0};

typedef struct { const u8* data; u32 pos; u32 size; } PngReader;
static void png_read_mem(png_structp png, png_bytep out, png_size_t count) {
    PngReader* r = (PngReader*)png_get_io_ptr(png);
    if (r->pos + count > r->size) count = r->size - r->pos;
    memcpy(out, r->data + r->pos, count);
    r->pos += count;
}

static void load_pack(int idx) {
    if (s_inited[idx]) return;
    const u8* data = g_pack_atlases[idx];
    u32 size = g_pack_sizes[idx];

    png_structp png = png_create_read_struct(PNG_LIBPNG_VER_STRING, NULL, NULL, NULL);
    png_infop info  = png_create_info_struct(png);
    PngReader reader = { data, 0, size };
    png_set_read_fn(png, &reader, png_read_mem);
    png_read_info(png, info);

    int w = png_get_image_width(png, info);
    int h = png_get_image_height(png, info);
    s_atlasW[idx] = w;
    s_atlasH[idx] = h;

    png_set_strip_16(png);
    png_set_expand(png);
    if (png_get_color_type(png, info) == PNG_COLOR_TYPE_RGB)
        png_set_filler(png, 0xFF, PNG_FILLER_AFTER);
    png_read_update_info(png, info);

    u8* rgba = (u8*)malloc(w * h * 4);
    png_bytep* rows = (png_bytep*)malloc(h * sizeof(png_bytep));
    for (int y = 0; y < h; y++) rows[y] = rgba + y * w * 4;
    png_read_image(png, rows);
    free(rows);
    png_destroy_read_struct(&png, &info, NULL);

#ifdef _PC
    GX_InitTexObj(&s_atlasObjs[idx], rgba, w, h, GX_TF_RGBA8, GX_CLAMP, GX_CLAMP, GX_FALSE);
    free(rgba);
#else
    u32 gxSize = w * h * 4;
    u8* gxBuf  = (u8*)memalign(32, gxSize);
    int tileW=(w+3)/4, tileH=(h+3)/4;
    u8* dst = gxBuf;
    for (int ty=0;ty<tileH;ty++) for (int tx=0;tx<tileW;tx++) {
        for (int py=0;py<4;py++) for (int px=0;px<4;px++) {
            int sx=tx*4+px, sy=ty*4+py;
            u8* p=(sx<w&&sy<h)?rgba+(sy*w+sx)*4:(u8*)"\xFF\0\0\xFF";
            *dst++=p[3]; *dst++=p[0];
        }
        for (int py=0;py<4;py++) for (int px=0;px<4;px++) {
            int sx=tx*4+px, sy=ty*4+py;
            u8* p=(sx<w&&sy<h)?rgba+(sy*w+sx)*4:(u8*)"\xFF\0\0\xFF";
            *dst++=p[1]; *dst++=p[2];
        }
    }
    free(rgba);
    DCFlushRange(gxBuf, gxSize);
    GX_InitTexObj(&s_atlasObjs[idx], gxBuf, w, h, GX_TF_RGBA8, GX_CLAMP, GX_CLAMP, GX_FALSE);
#endif
    GX_InitTexObjFilterMode(&s_atlasObjs[idx], GX_NEAR, GX_NEAR);
    s_inited[idx] = 1;
}

void Tex_Init() {
    // Load active pack only — others loaded on demand when switched
    load_pack(s_currentPack);
}

void Tex_BindAtlas() {
    GX_LoadTexObj(&s_atlasObjs[s_currentPack], GX_TEXMAP0);
}

static TexRegion s_cache[TEX_COUNT];
static int s_cache_built = 0;
static void tex_reset_cache() { s_cache_built = 0; }

void Tex_Switch(int packIndex) {
    if (packIndex < 0 || packIndex >= PACK_COUNT) return;
    if (packIndex == s_currentPack) return;
    load_pack(packIndex);
    s_currentPack = packIndex;
    tex_reset_cache();
}

int  Tex_GetPackCount()            { return PACK_COUNT; }
const char* Tex_GetPackName(int i) { return (i>=0&&i<PACK_COUNT) ? g_pack_names[i] : ""; }
int  Tex_GetCurrentPack()          { return s_currentPack; }

const TexRegion* Tex_GetRegion(int texID) {
    if (!s_cache_built) {
        int idx = s_currentPack;
        float insetU = 0.5f / (float)s_atlasW[idx];
        float insetV = 0.5f / (float)s_atlasH[idx];
        for (int i = 0; i < TEX_COUNT; i++) {
            s_cache[i] = {
                atlas_uvs[i][0] + insetU,
                atlas_uvs[i][1] + insetV,
                atlas_uvs[i][2] - insetU,
                atlas_uvs[i][3] - insetV
            };
        }
        s_cache_built = 1;
    }
    return &s_cache[texID];
}